# Generated by Django 5.0 on 2024-01-17 10:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coursepg', models.CharField(max_length=150)),
                ('schoolclgpg', models.CharField(max_length=300, null=True)),
                ('yearofpassingpg', models.CharField(max_length=100, null=True)),
                ('persentagepg', models.CharField(max_length=50, null=True)),
                ('coursegra', models.CharField(max_length=150)),
                ('schoolclggra', models.CharField(max_length=300, null=True)),
                ('yearofpassinggra', models.CharField(max_length=100, null=True)),
                ('persentagegra', models.CharField(max_length=50, null=True)),
                ('coursessc', models.CharField(max_length=150)),
                ('schoolclgssc', models.CharField(max_length=300, null=True)),
                ('yearofpassingssc', models.CharField(max_length=100, null=True)),
                ('persentagessc', models.CharField(max_length=50, null=True)),
                ('coursehsc', models.CharField(max_length=150)),
                ('schoolclghsc', models.CharField(max_length=300, null=True)),
                ('yearofpassinghsc', models.CharField(max_length=100, null=True)),
                ('persentagehsc', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmployeeExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company1name', models.CharField(max_length=150)),
                ('company1desig', models.CharField(max_length=300, null=True)),
                ('company1salary', models.CharField(max_length=100, null=True)),
                ('company1duration', models.CharField(max_length=50, null=True)),
                ('company2name', models.CharField(max_length=150)),
                ('company2desig', models.CharField(max_length=300, null=True)),
                ('company2salary', models.CharField(max_length=100, null=True)),
                ('company2duration', models.CharField(max_length=50, null=True)),
                ('company3name', models.CharField(max_length=150)),
                ('company3desig', models.CharField(max_length=300, null=True)),
                ('company3salary', models.CharField(max_length=100, null=True)),
                ('company3duration', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
