# Generated by Django 5.0 on 2024-01-18 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employeeexperience_company1name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeeeducation',
            old_name='persentagegra',
            new_name='percentagegra',
        ),
        migrations.RenameField(
            model_name='employeeeducation',
            old_name='persentagehsc',
            new_name='percentagehsc',
        ),
        migrations.RenameField(
            model_name='employeeeducation',
            old_name='persentagessc',
            new_name='percentagepg',
        ),
        migrations.RenameField(
            model_name='employeeeducation',
            old_name='persentagepg',
            new_name='percentagessc',
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='coursegra',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='coursehsc',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='coursepg',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='coursessc',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
